[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "colour-science==0.3.16",
	"numpy",
	"scipy",    
	"pynverse",  
	"matplotlib>=3.3.4",
	"networkx>=2.5" 
]
build-backend = "setuptools.build_meta"